version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    # command: >
    #   bash -c 'mongosh "mongodb://root:example@localhost:27017/admin" /docker-entrypoint-initdb.d/init-mongo.js && mongod --bind_ip_all'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mynetwork
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - mynetwork
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb_data:

networks:
  mynetwork:
